export enum ResponseStatus {
    NOT_FOUND_QUESTIONS = "NOT_FOUND_QUESTIONS",
    NOT_FOUND_USER = "NOT_FOUND_USER",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    BAD_REQUEST = "BAD_REQUEST",
    REVOKED_TOKEN = "REVOKED_TOKEN",
    SESSION_EXPIRED = "SESSION_EXPIRED",
    UNAUTHORIZED = "UNAUTHORIZED",

    // * Success response status
    USER_UPDATED = "USER_UPDATED",
    CORRECT = "CORRECT",

    // * Pending to action status
    WAITING_FOR_AUTHENTICATION = "WAITING_FOR_AUTHENTICATION",
}